services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${XDM_DB_NAME}
      MYSQL_USER: ${XDM_DB_USER}
      MYSQL_PASSWORD: ${XDM_DB_PASSWORD}
    ports:
      - "${XDM_DB_PORT}:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "${XDM_REDIS_PORT}:6379"

  rabbitmq:
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - "${XDM_RABBITMQ_PORT}:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${XDM_RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${XDM_RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  minio:
    image: minio/minio:latest
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --address "0.0.0.0:9000" --console-address "0.0.0.0:9001"
    environment:
      MINIO_ROOT_USER: ${XDM_S3_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${XDM_S3_SECRET_KEY}
    volumes:
      - minio-data:/data

volumes:
  mysql-data:
  rabbitmq-data:
  minio-data:
